- job:
    name: calculator_job1
    run: playbooks/calculator_job1.yaml
- job:
    name: calculator_test_job
    run: playbooks/calculator_test_job.yaml

- project:
    check:
      jobs:
        - calculator_job1
        - calculator_test_job
        
- project:
    check:
      jobs:
        - noop
