- job:
    name: testjob
    run: playbooks/testjob.yaml
- job:
    name: testjob2
    run: playbooks/testjob2.yaml

- project:
    check:
      jobs:
        - testjob
        - testjob2
        
- project:
    check:
      jobs:
        - noop
