- job:
    name: hello_world
    run: playbooks/hello_world.yaml
- job:
    name: calculator_test_job
    run: playbooks/calculator_test_job.yaml

- project:
    check:
      jobs:
        - hello_world
        - calculator_test_job
        
- project:
    check:
      jobs:
        - noop
