- job:
    name: calculator_job
    run: playbooks/calculator_job.yaml
- job:
    name: calculator_test_job
    run: playbooks/calculator_test_job.yaml

- project:
    check:
      jobs:
        - calculator_job
        - calculator_test_job
        
- project:
    check:
      jobs:
        - noop
