- job:
    name: testjob
    run: playbooks/testjob.yaml
- job:
    name: calculator_test_job
    run: playbooks/calculator_test_job.yaml

- project:
    check:
      jobs:
        - testjob
        - calculator_test_job
        
- project:
    check:
      jobs:
        - noop
