- hosts: all
  tasks:
    - name: test
      shell: |
             cd playbooks
             ls -a
             echo "Runing unit test for add.py which is dynamic code getting 2 argument in command line"
             python ./github/zuultesting4/playbooks/cal.py
             
